services:
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - auth_net

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --innodb-buffer-pool-size=512M --max-connections=300
    environment:
      MYSQL_DATABASE: zwaidb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth_net

  backend:
    build: .
    container_name: zerowasteai_api
    volumes:
      - .:/app
      - ./src/config/firebase_credentials.json:/app/src/config/firebase_credentials.json
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      FLASK_APP: src/main.py
      FLASK_ENV: production
      REDIS_URL: redis://redis:6379/0
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: zwaidb
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: userpass
      DB_NAME: zwaidb
      FIREBASE_CREDENTIALS_PATH: src/config/firebase_credentials.json
      FIREBASE_STORAGE_BUCKET: zer0wasteai-91408.firebasestorage.app
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    networks:
      - auth_net

volumes:
  mysql_data:

networks:
  auth_net: